name: sclak
favicon: null
layout_spectrum: 0.04459741176106036
typography_spectrum: 0.8240289033856243
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3369440452661365
  lightness: 0.9392482328694314
  saturation: 0.8173646805807948
  rhythmicContrast: 0.7403610527981073
purpose: []
